### PR TITLE
[UX] settings close floating button, fix tokens position auto suggest prompt, AutoSuggest minor bugs

### PR DESCRIPTION
**Pull request by ljh5650**
# PR Checklist
- [ - ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ O ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ O ] Did you added a type def?

# Description
There are many users who can't find the character deletion, so it has been changed so that it is clearly visible in the header.
스크린샷 2023-06-03 004117
스크린샷 2023-06-03 004122

It is inconvenient to scroll up and close the long settings window when scrolling, so it is fixed at the top.
스크린샷 2023-06-03 002151

Modify tokens count position not moved together auto suggest prompt.
스크린샷 2023-06-03 002350

Fixed the problem that auto-suggestion does not work for firstMessage
Fixed the problem that auto-suggestion is not saved

### CODE REVIEW

**Comment by kwaroran** [comment]
Even if it's hard to find the delete button, I don't think it's good to add it to the header,
There are already too many buttons in the header, and it becomes more complicated.

**Comment by Alwaysfindtheway** [comment]
This has caused quite a few people to become confused and unable to find the Delete Character button.

**Comment by ljh5650** [comment]
> Could you revert the deletion menu?
> 
> Even if it's hard to find the delete button, I don't think it's good to add it to the header, There are already too many buttons in the header, and it becomes more complicated.

@kwaroran 
Deletion ui separation commit reverted.

How about improving the Edit Order feature with the ability to display a deleteable x button in the sidebar?
It seems easier to find than at the bottom of the Advanced Settings.
스크린샷 2023-06-03 172219

**Comment by drPpZero** [comment]
> > Could you revert the deletion menu?
> > Even if it's hard to find the delete button, I don't think it's good to add it to the header, There are already too many buttons in the header, and it becomes more complicated.
> 
> @kwaroran Deletion ui separation commit reverted.
> 
> How about improving the Edit Order feature with the ability to display a deleteable x button in the sidebar? It seems easier to find than at the bottom of the Advanced Settings.

I don't think this is a good idea. The delete button should be in the character's sidebar.

**Pull request merged**
