### PR TITLE
[fix] oobabooga

### PR DESCRIPTION
**Pull request by aegkmq**
# PR Checklist
- [x] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [x] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [x] Did you added a type def?

# Description
- Fix the sampling parameter inputs and remove unused settings (#224)
- Add the streaming features
- Force to use the model's prompt template
- Strict end-of-text checking with many stop strings
- Replace the oobabooga prebuilt preset with simple-1 (oobabooga preset arena winner)
- Increase the default oobabooga truncation length from 2048 to 4096 (LLaMA 1 -> LLaMA 2)

### CODE REVIEW

**Comment by aegkmq** [comment]
Work in progress...

**Comment by aegkmq** [comment]
@kwaroran Can you check the PR?

**Comment by aegkmq** [comment]
Oh I need a little more work.

**Comment by kwaroran** [comment]
mention again when you are done

**Comment by aegkmq** [comment]
@kwaroran I think I finished now.

**Pull request merged**
