### PR TITLE
HypaV2 context deletion safety

### PR DESCRIPTION
**Pull request by LightningHyperBlaze45654**
# PR Checklist
- [x] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions? << Checked on browser only, works fine
- [x] Did you added a type def?

# Description
HypaV2 data's large type definition update.
```ts
    mainChunks: { // summary itself
        id: number;
        text: string;
        chatMemos: Set<string>; // UUIDs of summarized chats
        lastChatMemo: string;
    }[];
    chunks: { // split mainChunks for retrieval or something. Although quite uncomfortable logic, so maybe I will delete it soon.
        mainChunkID: number;
        text:string;
    }[];
```
With this, ensure that mainChunks is relevant on chat context change by deletion

If there is no UUID in the chat context, but it exists on chatMemos on certain mainChunk, removes it.

Changed index.svelte.ts to update args on each call to ensure hypav2 to stay adaptive on this change without refreshing the page

Also changed mainChunks to be pushed instead of unshifted

### CODE REVIEW

**Comment by kwaroran** [comment]
Is this compatible with existing saves? or does it have a conversion process?

**Comment by LightningHyperBlaze45654** [comment]
> Is this compatible with existing saves? or does it have a conversion process?

Since there is a data change, existing chat's hypav2 would be redundant(invalid)

It requires conversion, however I do not think it will be achieved easily.

**Comment by LightningHyperBlaze45654** [comment]
Current interface of HypaV2 looks like this:
```
export interface HypaV2Data {
    chunks: {
        text: string;
        targetId: string;
    }[];
    mainChunks: {
        text: string;
        targetId: string;
    }[];
}
```
And considering the targetId is the last chat's memo of summary, conversion function can be made.

**Comment by kwaroran** [comment]
It will need conversion or separation because it might break existing chats, which leads to a bad UX  in my opinion.

**Comment by LightningHyperBlaze45654** [comment]
I'll revise the code to check if the type is previous one. And convert it to newly upgraded version.

If memo does not exist, it will also sanitize itself

**Comment by LightningHyperBlaze45654** [comment]
Re-opened the brach as conversion function has been added

It works on the init of HypaV2

**Comment by LightningHyperBlaze45654** [comment]
@kwaroran does it check out? Is it okay?

**Pull request merged**
